### ISSUE TITLE
@Skip doesn't work on jbehave and Serenity

### ISSUE THREAD

**Issue by maforast** [serenity-bdd/serenity-jbehave#146] opened 2017-12-13 11:08 UTC
Hi, 
I spent 2 days to configure @skip scenario on jbhave and serenity. I'm using Junit runner and skipped message is correctly write on console output, but @step method is not skipped.

I'don't understand what I have to configure 

Can you help me?

Tnx in advance

**Comment by wakaleo** [comment] 2017-12-13 11:10
What do you mean, the @Step method is not skipped? How do you know?

**Comment by maforast** [comment] 2017-12-13 12:00
`public class MessageAcquisitionStepDefinitions {

	@Steps
    MessageAcquisitionSteps process;
	
	
			
    @Given("A message $inputmessage has been submitted for survey $survey by user $user for observed agent $oa")
    public void submitSpecificMessageFromClient(String messageId, String survey, String user, String oa) {
    	process.selectSubmittedMessage(messageId,survey, user, oa);
    }

    
    @When("The platform in environment $env tries to acquire the submitted message")
    public void lauchMessageAcquisition(String env) throws Throwable {
    	process.invokeServerFarmServicesFlow(env);
    }
`

Story

`Discard a message with xml not well formed

Meta:
@driver Firefox

Narrative:
  In order to check incorrect messages in conversion phase 
  As Anacredit Collection Platform
  I have to discard messages not well formed

Scenario: The message is discarded in conversion phase because of an error in xml validation (not-well-formed)
Meta:
@skip
@ignored true
Given A message NOT_WELL_FORMED_FRAGMENT.xml has been submitted for survey T1M by user A2A-27627519 for observed agent 503235
When The platform in environment svil tries to acquire the submitted message
Then The message is discarded in conversion phase with remark text containing 'NOT_WELL_FORMED_FRAGMENT'
`

**Comment by wakaleo** [comment] 2017-12-13 13:32
In Serenity JBehave, `@skip` and `@ignore` should be in lower case, and `@ignore` does not take a parameter (so not `@ignore true`).

**Comment by maforast** [comment] 2017-12-13 14:16
I have correctly @skyp in lower case in all my story that I want to skip, but result is the same:

2970 [pool-1-thread-1] INFO net.serenitybdd.core.Serenity - TEST SKIPPED
2971 [pool-1-thread-1] INFO net.serenitybdd.core.Serenity - TEST IGNORED
2972 [pool-1-thread-1] INFO net.serenitybdd.core.Serenity - TEST SKIPPED
2973 [pool-1-thread-1] INFO net.serenitybdd.core.Serenity - TEST IGNORED
Given A message NOT_WELL_FORMED_FRAGMENT.xml has been submitted for survey T1M by user A2A-27627519 for observed agent 503235
Cannot lookup appName and module name in logger --> setting common component for CommonLogger

Log write skipped but the method @when is called in all skipped scenaries

**Comment by wakaleo** [comment] 2017-12-13 14:18
What versions are you using?

**Comment by maforast** [comment] 2017-12-13 14:20
My pom
```
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<webdriver.driver>firefox</webdriver.driver>
		<serenity.version>1.8.5</serenity.version>
		<serenity.maven.version>1.8.5</serenity.maven.version>
		<serenity.junit.version>1.8.5</serenity.junit.version>
		<serenity.jbehave.version>1.34.0</serenity.jbehave.version>
	
	</properties>
```

**Comment by wakaleo** [comment] 2017-12-13 14:32
Are you executing code in your @When step that is not encapsulated in a @Step method?

**Comment by maforast** [comment] 2017-12-13 14:44
As you can see  above, I declared `@Steps MessageAcquisitionSteps process;`

and in MessageAcquisitionSteps i have @step method as:

`	@Step                                                       
    public void selectSubmittedMessage(String messageId,String survey,String user,String oa) {
		....
    }
	
	@Step
    public void invokeServerFarmServicesFlow(String environment) throws Throwable {
...}
`
I expect these steps was ignored or skiped, but when I run test in debug, this method steps was called.

**Comment by wakaleo** [comment] 2017-12-13 14:51
I can't reproduce this, I would have to see a sample project reproducing the issue or look directly at your code.

**Comment by maforast** [comment] 2017-12-13 14:59
Tnx for reply, I have problem to share my code, but what i wont to know, if this is correct mode to skip scenary in serenity - jbheave or there is something wrong or I missing in my configuration.

**Comment by wakaleo** [comment] 2017-12-13 16:47
From what I can see what you are doing should work.

**Comment by maforast** [comment] 2017-12-13 17:22
You are right, I think so too, that is the big question that freak me out!! Are you sure that there aren't any configuration to inject in java class of my stories as explained here http://jbehave.org/reference/stable/dependency-injection.html ?

**Comment by maforast** [comment] 2017-12-15 10:46
Any news on my previous post?

**Comment by wakaleo** [comment] 2017-12-15 11:10
You will probably need to dive into the code on your side to see what it is doing.

**Comment by maforast** [comment] 2017-12-15 11:18
I downloaded, test framework from https://github.com/serenity-bdd/serenity-jbehave, I see that you create a class as WhenDeclaringManualScenarios extends SerenityStory {} for each story.
I instead have only one class DiscardAcceptanceTests extends SerenityStories and one Steps process for 5 different story.
MayBe is this?

**Comment by maforast** [comment] 2017-12-15 13:30
I'm try with your test framework from https://github.com/serenity-bdd/serenity-jbehave, and isue rise up here too.

![serenitysmokedebug](https://user-images.githubusercontent.com/15627875/34044231-7056ff38-e1a4-11e7-87de-9e1f877f3f13.png)

as you can see, console show skiped, but debug go in @when step scenario

**Comment by wakaleo** [comment] 2017-12-15 13:32
This is normal behaviour; Serenity will step through the @Given, @When and @Then methods, but not execute any @Step methods or WebDriver calls.

**Comment by maforast** [comment] 2017-12-15 13:39
As you can see it go inside step too:

![stepsinside](https://user-images.githubusercontent.com/15627875/34044587-d1df88d2-e1a5-11e7-9713-3f24e1211ca6.png)

**Comment by wakaleo** [comment] 2017-12-15 13:41
So far this is normal. Serenity doesn't skip steps, it just runs them in "disabled" mode. That's how it generates the in-depth reports. If you don't want it to step into the implementation of a `@Step` method, use `@Step(callNestedMethods=true)`.

**Comment by maforast** [comment] 2017-12-15 13:52
I don't want skipped annotated scenario was executed!
I'm trying to put @Step(callNestedMethods=true) on steps that I don't want to be executed but nothing happen all steps was executed in skip scenario. :(

**Comment by maforast** [comment] 2017-12-15 14:00
Ok maybe with @Step(callNestedMethods=false) it work

**Comment by wakaleo** [comment] 2017-12-15 14:01
Consider this code:

```
public class StepDefinitions {

	@Steps
	TestSteps steps;

	@When("print '$value'")
	public void print(String value) {
		System.out.println("WHEN STEP FOR " + value);
		steps.print(value);
	}
}

public static class TestSteps {

	@Step(callNestedMethods = false)
	public void print(String value) {
		System.out.println("INSIDE STEP WITH VALUE " + value);
	}
}
```

And this scenario:

```
Scenario: scenario 1
Meta:
@skip
When print '1'
```

The output will be "WHEN STEP FOR 1

But not "INSIDE STEP WITH VALUE 1"

**Comment by wakaleo** [comment] 2017-12-15 14:02
Because Serenity can control step execution, but not JBehave execution

**Comment by maforast** [comment] 2017-12-15 14:04
:+1:  ok with @Step(callNestedMethods=false) it perform skip step scenario, this is bheaviour that I want expected.

Tnx so much

**Comment by wakaleo** [comment] 2017-12-15 14:05
OK, thanks for the feedback, I will close this issue then.

**Closed by wakaleo** 2017-12-15 14:05 UTC
