### ISSUE TITLE
No BaseStepListener has been registered when error happens in Before/AfterStories

### ISSUE THREAD

**Issue by mathieudruart** [serenity-bdd/serenity-jbehave#13] opened 2015-06-03 15:07 UTC
Hello,

Thank you for your awesome framework !

I've got an issue generating the Serenity report when there is an error in JBehave AfterStories or BeforeStories, it's a NullPointerException :

java.lang.RuntimeException: java.lang.NullPointerException: No BaseStepListener has been registered
    at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:161)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException: No BaseStepListener has been registered
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
    at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:94)
    at net.thucydides.core.steps.StepEventBus.updateCurrentStepTitle(StepEventBus.java:462)
    at net.serenitybdd.jbehave.SerenityReporter.failed(SerenityReporter.java:669)
    at org.jbehave.core.reporters.DelegatingStoryReporter.failed(DelegatingStoryReporter.java:103)
    at org.jbehave.core.reporters.ConcurrentStoryReporter.failed(ConcurrentStoryReporter.java:275)
    at org.jbehave.core.steps.AbstractStepResult$Failed.describeTo(AbstractStepResult.java:40)
    at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:319)
    at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1012)
    at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:401)
    at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:128)
    at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:105)
    at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:84)
    at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:208)
    at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:159)

I'm using jbehave-core 4.0, serenity-jbehave 1.0.21 and net.serenity-bdd core 1.0.47.

**Comment by wakaleo** [comment] 2015-06-04 12:10
Thanks, I'll take a look.

**Comment by anujbajaj** [comment] 2015-07-30 18:49
Dear Wakaleo,

Do we have any update on the issue mentioned above?

Regards,
Anuj

**Comment by rameshsaketi** [comment] 2015-11-20 19:43
Any update on this issue ? Trying ti migrate from basic JUnitStories to SerenityStories.

This is stopping us to migrate towards serenity ...

Here is the error stack trace :

ASSteps.initializeActiveSpaces() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method initializeActiveSpaces (annotated with @BeforeStories in class com.wave.storySteps.WMSASSteps) failed: net.serenitybdd.jbehave.SerenityStepInitializationError: java.lang.InstantiationException)
Generating reports view to 'C:\SerinityWorkbench\target\jbehave' using formats '[stats, console, txt, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 3 stories (of which 0 pending) containing 2 scenarios (of which 0 pending)
java.lang.RuntimeException: java.lang.NullPointerException: No BaseStepListener has been registered
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:161)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException: No BaseStepListener has been registered
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:95)
	at net.thucydides.core.steps.StepEventBus.updateCurrentStepTitle(StepEventBus.java:463)
	at net.serenitybdd.jbehave.SerenityReporter.failed(SerenityReporter.java:669)
	at org.jbehave.core.reporters.DelegatingStoryReporter.failed(DelegatingStoryReporter.java:103)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.failed(ConcurrentStoryReporter.java:275)
	at org.jbehave.core.steps.AbstractStepResult$Failed.describeTo(AbstractStepResult.java:40)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:335)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1042)
	at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:420)
	at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:117)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:159)
	... 6 more

**Comment by mark-lacdao** [comment] 2016-01-25 06:29
Hello @wakaleo ,

Do you have any updates regarding this issue? I am currently experiencing the same error, been trying to migrate from thucydides to serenity.

Thanks in advance.

**Comment by YamStranger** [comment] 2016-01-25 07:50
Hello @mark-lacdao. 

There is no updates for this issue, for now.

Is it possible to use exception-save code in @Before/AfterStories in your situation? 
Just as question - I like when constructor of class never throw exception (no exception during initialization, only during executing),  and test have same phase - initialization, execution, and initialization should be successful, only execution part can fail ) What do you think about it? 
P.S. It is not about fix, just thoughts.  

Thanks

**Comment by YamStranger** [comment] 2016-05-03 05:55
@mathieudruart Please try latest serenity core and jbehave. 
If it will solve your problem please close this ticket.
Thansk!

**Comment by mathieudruart** [comment] 2016-05-11 18:37
@YamStranger thank you for the update, we tried the last version but we are stuck with another problem, see my comment on #72

**Comment by mrunalgosar** [comment] 2016-11-07 13:23
I am also facing the same issue as mentioned above. I have been using the latest serenity deps i.e 1.14.0 which internally uses all the latest JBehave libraries. This issue is stopping me from using serenity. Can we look at fixing this or atleast give me a pointer to where to look in the serenity source code and i can try and fix this.

**Closed** 2016-12-14 20:58 UTC
Labels: bug
