### ISSUE TITLE
Annotated Before and AfterScenarios do not run

### ISSUE THREAD

**Issue by spcial** [serenity-bdd/serenity-jbehave#113] opened 2017-01-24 08:35 UTC
Hi!

We used an older version of serenity-jbehave for our serenity BDD Tests (1.1.0). But while the grouping feature was not working correctly with this version I updated the version to the latest one (1.21.0). After the update the grouping feature works fine but our methods wich are annotated with @BeforeScenario or @AfterScenario (or any other annotation) do not run anymore. We are using a seperate file for this scenarios: SetupAndTeardownBDD.java which looks like this (imports removed):

public class SetupAndTeardownBDD{
	

	@Steps
	protected KonzernpostkorbSteps benutzer;
	
	/*********************
	 * 
	 * Before
	 * 
	 *********************/
	
	@BeforeScenario
	public void storeSessionId() {
		//do something
	}
	
	@BeforeScenario
	public void initListeVerteilteAufgaben() {
		//do something
	}
	
	
	/*********************
	 * 
	 * After
	 * 
	 *********************/
	@AfterScenario
	public void schliesseAufgabeUnderTestAb() {
		//do something
	}
	
	@AfterScenario
	public void sessionVariablenZuruecksetzen() {
		//do something
	}	
	
	//some protected internal methods
}
`

Was there any change after the 1.1.0 version regarding the structure or annotation? I tried some other verisons but it seems that every version after 1.1.0 do not run any before or aftermethods.

thanks

**Comment by spcial** [comment] 2017-01-24 09:18
I checked again and found out that 1.6.0 is working but 1.8.0 not. Any changes between this both releases regarding before and after-methods?

**Comment by wakaleo** [comment] 2017-01-24 09:57
What version of JBehave are you using?

**Comment by spcial** [comment] 2017-01-24 11:00
I was speaking about the serenity-jbehave version all the time: 1.6.0 is working -> 1.7.0 is not working for me (in terms of before and after annotations). For serenity-core I use 1.2.2. 

See my POM-file:

````
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>xy</groupId>
	<artifactId>xy</artifactId>
	<name>xy</name>
	<version>0.1.0-SNAPSHOT</version>
	<packaging>jar</packaging>


	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    	<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<serenity.version>1.2.2</serenity.version>
		<serenity.maven.version>1.2.2</serenity.maven.version>
		<serenity.jbehave.version>1.6.0</serenity.jbehave.version>
		<phantomjs-maven-plugin.version>0.7</phantomjs-maven-plugin.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jbehave</artifactId>
			<version>${serenity.jbehave.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.12</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.1.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>2.8.2</version>
		</dependency>

		//some other internal dependencies
	
	</dependencies>
	<build>
		<plugins>
			 <plugin>
	        <groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-compiler-plugin</artifactId>
	        <version>3.2</version>
	        <configuration>
	          <source>1.7</source>
	          <target>1.7</target>
	        </configuration>
	      </plugin>
			<plugin>
				<groupId>com.github.klieber</groupId>
				<artifactId>phantomjs-maven-plugin</artifactId>
				<version>${phantomjs-maven-plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>install</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<version>1.9.8</version>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<argLine>-Dphantomjs.binary.path=${phantomjs.binary}</argLine>
					<testFailureIgnore>true</testFailureIgnore>
					<includes>
						<include>**/*Test.java</include>
						<include>**/Test*.java</include>
						<include>**/When*.java</include>
						<include>**/*TestSuite.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<configuration>
							<requirementsBaseDir>./target/requirements</requirementsBaseDir>
						</configuration>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>ENTW</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>process-test-resources</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<tasks>
										<copy todir="target/test-classes">
											<fileset dir="properties/ENTW">
												<include name="**/*.*" />
											</fileset>
										</copy>
									</tasks>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>FATE</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>process-test-resources</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<tasks>
										<copy todir="target/test-classes">
											<fileset dir="properties/FATE">
												<include name="**/*.*" />
											</fileset>
										</copy>
									</tasks>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>AETE</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<executions>
							<execution>
								<phase>process-test-resources</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<tasks>
										<copy todir="target/test-classes">
											<fileset dir="properties/AETE">
												<include name="**/*.*" />
											</fileset>
										</copy>
										<copy todir="target/requirements/src/test/resources">
											<fileset dir="src/test/resources">
												<include name="**/*.*" />
											</fileset>
										</copy>
									</tasks>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>`

**Comment by wakaleo** [comment] 2017-01-24 13:45
Try using the latest version of serenity-jbehave, which is currently 1.21.0: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22serenity-jbehave%22

**Comment by wakaleo** [comment] 2017-01-25 08:25
I can't reproduce this, could you provide a sample project?

**Comment by spcial** [comment] 2017-02-01 11:23
Actually this is quite dificult: I cannot upload the current project because it is used in our company and includes internal links / users / password and uses also interfaces and services and has therefore a lot of dependencies wich could not be resolved outside our environment. So I would actually had to set up a completely new project....

but probably you can take a look at the jbehave configuration in the test suite:

```
public class KPKAcceptanceTestSuite extends SerenityStories {

    private final Locale DEFAULTSTORYLANGUAGE = Locale.GERMAN;

    public KPKAcceptanceTestSuite() {
        System.setProperty("restart.browser.each.scenario", "true");
    }

    @Override
    public Configuration configuration() {
        Configuration configuration = super.configuration();
        
        Keywords keywords = new LocalizedKeywords(DEFAULTSTORYLANGUAGE);
        Properties properties = configuration.storyReporterBuilder().viewResources();
        properties.setProperty("encoding", "UTF-8");
        
        configuration.useKeywords(keywords)
                .useStoryParser(new RegexStoryParser(keywords, new ExamplesTableFactory(new LocalizedKeywords(DEFAULTSTORYLANGUAGE), new LoadFromClasspath(this.getClass()), new ParameterConverters())))
                .useStoryLoader(new UTF8StoryLoader())
                .useStepCollector(new MarkUnmatchedStepsAsPending(keywords))
                .useDefaultStoryReporter(new ConsoleOutput(keywords))
                .storyReporterBuilder()
                .withKeywords(keywords)
                .withViewResources(properties);

        return configuration;
    }
    
}
```

I'm not sure if there is a mistake because the jbehave documentation is not very detailed in terms of options and possibilities. 

I also checked all the versions and dependencies and updated them to the latest one but the error still occurs.

Looking at the console output I can see that e.g. "(AfterStories)" occurs in the output but nothing is done. I also found another bug. Looking into the report in the scenario outline I can find this behaviour:

![image](https://cloud.githubusercontent.com/assets/13414244/22504929/0f78ce1e-e879-11e6-92e9-d2b9c85b13d6.png)

You see that there is a "<SPARTE>" before and after every word. So I assume probably something is wrong with my configuration? Btw the keyword SPARTE is used in the example tables and can be empty sometimes.

Do you have any suggestions what I could try?

**Comment by spcial** [comment] 2017-02-06 13:54
Small addition: The error with the scenario outline (<SPARTE> is added everywhere) is happening when I have an example table and in a dateset a column-value is not filled (e.g. because it is not needed).

e.g.: 
![image](https://cloud.githubusercontent.com/assets/13414244/22649622/0fa9a712-ec7c-11e6-90b0-44f376c23c40.png)


when I put a value in K2 the error disappears.

**Comment by wakaleo** [comment] 2017-03-27 06:50
The JBehave API has changed, you now need to provide the `uponType` parameter, eg.

    @BeforeScenario(uponType = ScenarioType.ANY)
    public void setTheStage() {
        OnStage.setTheStage(new OnlineCast());
    }

The scenario outline issue is fixed in the latest version.

**Closed by wakaleo** 2017-03-27 06:50 UTC

**Comment by JungPham** [comment] 2021-07-24 14:24
Hi guys, I tried with @BeforeScenario before a public method but this method didn't run before each scenario, my version <jbehave-core.version>4.1</jbehave-core.version>. Any one can help me? I am so grateful if anyone can help me.
