### ISSUE TITLE
Dependencies are not found.

### ISSUE THREAD

**Issue by sanjuthomas** [serenity-bdd/serenity-jbehave#103] opened 2016-09-14 21:08 UTC
I generated the jbehave jumpstart maven project using the arch type catalog given below.

``` xml
<archetype>
       <groupId>net.serenity-bdd</groupId>
       <artifactId>serenity-jbehave-archetype</artifactId>
       <version>1.1.36</version>
       <repository>https://repo1.maven.org/maven2/net/serenity-bdd/</repository>
    </archetype>

While I ran the maven verify I got a bunch class not found one after another, I had to add a set of dependencies and still its asking for another one. 

Caused by: java.lang.IllegalArgumentException: Could not find or access class for org.codehaus.groovy.runtime.dgm

The dependencies that I had to add - 

`   <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.9.5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant</artifactId>
            <version>1.9.7</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.core</artifactId>
            <version>6.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.marshalling</groupId>
            <artifactId>jboss-marshalling</artifactId>
            <version>1.4.11.Final</version>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.2</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>1.7.10</version>
        </dependency>`

am I missing something? 
```

**Comment by im-zeeshan** [comment] 2016-09-14 21:58
Make sure the SerenityBDD & JBehave version are the same. Remove the forcefully added dependencies and then run 'mvn clean verify'.

**Comment by sanjuthomas** [comment] 2016-09-15 15:01
@im-zeeshan Thanks for looking into it. I generated the jumpstart app using the maven jebhave archtype. The first class not found was related to a mockito class. Are you suggesting that the jbehave jumpstart app will work just out of the box? and no need to change anything? I will try once again today and keep you posted.

**Comment by sanjuthomas** [comment] 2016-09-16 01:59
This is what I got when I generated the JBehave jumpstart, could you please tell the right versions for both?
```xml
  <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.36</serenity.version>
        <serenity.jbehave.version>1.13.0</serenity.jbehave.version>
        <webdriver.driver>firefox</webdriver.driver>
    </properties> 

This one resulted in - 
 java.lang.NoClassDefFoundError: org/mockito/asm/signature/SignatureVisitor

**Comment by sanjuthomas** [comment] 2016-09-20 21:23
@im-zeeshan

**Comment by oleg--manzhos** [comment] 2017-01-02 15:10
Have the same issues.
1. Created project from 
`mvn archetype:generate -Dfilter=net.serenity-bdd:serenity-jbehave-archetype`
and got 
 <serenity.version>1.1.36</serenity.version>
 <serenity.jbehave.version>1.13.0</serenity.jbehave.version>

2. did
`mvn compile`
and 
`mvn clean verify`
3. got the following issue:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (default) on project se: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/mockito/asm/signature/SignatureVisitor
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] at net.serenitybdd.jbehave.ClassFinder.loadClassWithName(ClassFinder.java:206)
[ERROR] at net.serenitybdd.jbehave.ClassFinder.findClassesInJar(ClassFinder.java:169)
[ERROR] at net.serenitybdd.jbehave.ClassFinder.findClasses(ClassFinder.java:141)
[ERROR] at net.serenitybdd.jbehave.ClassFinder.allClassesInPackage(ClassFinder.java:74)
[ERROR] at net.serenitybdd.jbehave.ClassFinder.fromPackage(ClassFinder.java:57)
[ERROR] at net.serenitybdd.jbehave.SerenityStepFactory.getCandidateClasses(SerenityStepFactory.java:61)
[ERROR] at net.serenitybdd.jbehave.SerenityStepFactory.stepsTypes(SerenityStepFactory.java:51)
[ERROR] at org.jbehave.core.steps.AbstractStepsFactory.createCandidateSteps(AbstractStepsFactory.java:34)
[ERROR] at net.serenitybdd.jbehave.SerenityStepFactory.createCandidateSteps(SerenityStepFactory.java:44)
[ERROR] at net.serenitybdd.jbehave.runners.SerenityReportingRunner.buildCandidateSteps(SerenityReportingRunner.java:253)
[ERROR] at net.serenitybdd.jbehave.runners.SerenityReportingRunner.createCandidateStepsWith(SerenityReportingRunner.java:208)
[ERROR] at net.serenitybdd.jbehave.runners.SerenityReportingRunner.createCandidateStepsWithNoMonitor(SerenityReportingRunner.java:216)
[ERROR] at net.serenitybdd.jbehave.runners.SerenityReportingRunner.getCandidateSteps(SerenityReportingRunner.java:199)
[ERROR] at net.serenitybdd.jbehave.runners.SerenityReportingRunner.buildDescriptionFromStories(SerenityReportingRunner.java:272)
[ERROR] at net.serenitybdd.jbehave.runners.SerenityReportingRunner.getDescriptions(SerenityReportingRunner.java:90)
[ERROR] at net.serenitybdd.jbehave.runners.SerenityReportingRunner.getDescription(SerenityReportingRunner.java:137)
[ERROR] at org.junit.runners.Suite.describeChild(Suite.java:123)
[ERROR] at org.junit.runners.Suite.describeChild(Suite.java:27)
[ERROR] at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:352)
[ERROR] at org.apache.maven.surefire.common.junit4.JUnit4ProviderUtil.createSuiteDescription(JUnit4ProviderUtil.java:113)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.createTestsDescription(JUnit4Provider.java:257)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.mockito.asm.signature.SignatureVisitor
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] ... 37 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Process finished with exit code 1

4. Made some googlings and found that problem can be in maven-failsafe-plugin:
5. Did the following changes in pom.xml:
```
<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
```
Changed 2.18.1 as in archetype to 2.19.1.
6. Got the following error:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.654 sec <<< FAILURE! - in org.dataart.AcceptanceTestSuite
org.dataart.AcceptanceTestSuite  Time elapsed: 0.654 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/mockito/asm/signature/SignatureVisitor
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
Caused by: java.lang.ClassNotFoundException: org.mockito.asm.signature.SignatureVisitor
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
```

Didn't find how to manage it

**Comment by wakaleo** [comment] 2017-11-02 09:04
(Closing, presume resolved).

**Closed by wakaleo** 2017-11-02 09:04 UTC
