### ISSUE TITLE
Serenity: Reporting Queries

### ISSUE THREAD

**Issue by anbajaj** [serenity-bdd/serenity-jbehave#115] opened 2017-03-02 04:12 UTC
Dear Team,

@wakaleo @YamStranger 

We are using Serenity 1.1.40 with JBehave 1.9.0 in our project & have below mentioned queries. Would appreciate your feedback on the same:

- Whenever we are using below meta tags, index.html is not showing Jira id against the story. Same behavior is seen for @manual annotation.  
Meta:
@pending
@issue ABC-1

- If we have opened a defect/bug for any given story in Jira, is this possible to show both of them in the report indicating one is story id & the other one is defect/bug opened for it. we have tried below syntax however it is not indicating which one is what (Here ABC-2 is a defect opened for story ABC-1 in Jira).
Meta:
@issue ABC-1,ABC-2

- In some older versions of Serenity, we were using HTML tags to make our reports for informative by using different steps colors (Information, warnings, errors etc.) which really helps the person who is analyzing the report. I know we can use markdown to achieve the same however it is not working for us on Step level (raised this concern in #100 ) & has it's own limitations (doesn't support colors). Is there any way to accomplish this?

- For a data driven test like mentioned below, if the tests is failing for the last set of data, the pie chart in index.html is not calculating the correct % of passed/failed tests. We resolved it by moving that row above in the table. Team can test it using below sample story (compare Number1 & Number2):
Examples:
|Number1|Number2|
|1|1|
|1|1|
|1|2|

- Is this possible to update this **serenity.project.name** at run time based on functionality under execution? We have tried this by setting System property but it didn't help

Thanks much for developing this awesome framework. Truly appreciate it!

Best,
Anuj

**Comment by anbajaj** [comment] 2017-03-03 16:08
Team: Did you get a chance to look at the pointers mentioned in the above issue?

Thanks,
Anuj

**Comment by wakaleo** [comment] 2017-03-04 17:37
Thanks for your questions. Firstly, please update to the latest versions (1.1.23-rc.5 and 1.21.0 respectively), as issues are often resolved in new releases.  
1) Try with the latest version, and please raise a separate issue if the problem persists.
2) Try using the @issues tag
3) This is not currently supported
4) Please try with the latest versions
5) Not currently

**Closed by wakaleo** 2017-03-04 17:37 UTC

**Comment by anbajaj** [comment] 2017-03-04 19:05
Thanks for the reply @wakaleo 

After updating to the latest version, we are getting below exceptions. index.html is getting generated however with 5 stories (all passed) however there are no steps executed.

java.lang.RuntimeException: 
org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
Test/Sprint15/Story1.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: Test/Sprint15/Story1.story
Test/Sprint15/Story2.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: Test/Sprint15/Story2.story
Test/Sprint15/Story3.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: Test/Sprint15/Story3.story
Test/Sprint15/Story4.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: Test/Sprint15/Story4.story
Test/Sprint15/Story5.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: Test/Sprint15/Story5.story
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed:

**Comment by wakaleo** [comment] 2017-03-04 19:14
This looks like a JBehave failure (org.jbehave.core.embedder.StoryManager$StoryExecutionFailed); look for other stack traces in the logs that might indicate the source of the problem.

**Comment by anbajaj** [comment] 2017-03-05 20:20
Hi @wakaleo 

That's the complete stack trace being generated. I tried with other JBehave versions keeping serenity version as the latest (1.1.23-rc.5) & It worked fine with 1.18.0. Looks like something is broken after that version.  Could you please advice here?

Couple of other points noticed as mentioned below:

- Scenario Outline is not getting generated correctly:

![image](https://cloud.githubusercontent.com/assets/25538772/23590910/f7ae8230-01ad-11e7-9af5-5ad35d8f7f08.png)

- Markdown is working fine as step level as well. We are getting text as marked as bold or based on the markdown syntax.

Thanks,
Anuj

**Comment by wakaleo** [comment] 2017-03-05 20:27
can you provide a sample project to reproduce the issue?

**Comment by anbajaj** [comment] 2017-03-05 21:34
Hi @wakaleo 

Finally, I am able to reproduce the issue. Whenever we have an optional parameter in Examples Table, we are facing this issue. In the example posted above, DamageCode can be empty or can have a value & we can see that the scenario outline is writing<DamageCode>.

Please find attached a sample project. In the sample story, the example table looks like:

|NumberOne|NumberTwo|
||3|
|2|3|
|1||

![image](https://cloud.githubusercontent.com/assets/25538772/23591641/2615879e-01b9-11e7-88d4-4913f6292b03.png)


[Serenity.zip](https://github.com/serenity-bdd/serenity-jbehave/files/819764/Serenity.zip)

**Comment by anbajaj** [comment] 2017-03-05 23:57
Further to the above sample. this happens only when first data row has an empty parameter. It works fine after I moved that row below in the table.

**Comment by anbajaj** [comment] 2017-04-18 18:20
@wakaleo 

Did you get a chance to look into this issue? I have attached a sample project as well.

**Comment by wakaleo** [comment] 2017-04-18 20:45
Have you tried with the latest version?

**Comment by anbajaj** [comment] 2017-04-18 21:45
@wakaleo 

As soon as we are upgrading serenity-core to 1.2.4 & serenity-jbehave to 1.24.0, we are getting below exceptions. We tried by keeping serenity-core to 1.2.4 & changed serenity-jbehave version to 1.19.0 - 1.24.0, however getting the same exception. It is working fine with serenity-jbehave 1.18.0.

com.services.BaseServices  Time elapsed: 5.067 sec  <<< ERROR!
java.lang.RuntimeException: 
org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
stories/Test.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: stories/Test.story
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: 

This is our driver class - BaseServices :

runSerenity().inASingleSession();
        Embedder embedder = configuredEmbedder();
        //embedder.useStoryRunner(new StoryRunner());
        embedder
                .embedderControls()
                .doGenerateViewAfterStories(true)
                .doIgnoreFailureInStories(false)
                .doIgnoreFailureInView(true)
                .doVerboseFiltering(true)
                .useThreads(1);
        embedder.useMetaFilters(Collections.singletonList(System.getProperty("metafilter")));
        embedder.configuration().storyControls().doIgnoreMetaFiltersIfGivenStory(true);
        if (StringUtils.isNotEmpty(STORY_NAME))
            findStoriesCalled(STORY_NAME);
        else
            findStoriesIn(STORY_PATH);
