### ISSUE TITLE
Serenity is not executing the tests on the data rows added at run time.

### ISSUE THREAD

**Issue by anujbajaj** [serenity-bdd/serenity-jbehave#71] opened 2016-04-13 20:55 UTC
Dear Team,

We are using Serenity version 1.1.26 in our project & have been seeing an issue on trying to add table rows at the run time. We have created a custom listener which is adding the data row as below:

@Override
public void useExamplesFrom(DataTable table) {
    List<String> data = new ArrayList<>();
    data.add("abc");
    data.add("xyz");
    DataTableRow dataTableRow = new DataTableRow(data);
    table.addRow(dataTableRow);
}

In the Serenity report, it is showing 2 rows in the example table however it is running one row only. In the index.html, it is showing below data:

1 test scenarios (2 tests in all, including 2 rows of test data)
1 passed , 0 pending, 0 failed, 0 errors, 0 compromised, 0 ignored, 0 skipped [CSV]

Please note that pie chart is showing 100% passed however the stories section (on the right hand side of index.html), is showing 50% passed.

**Comment by anujbajaj** [comment] 2016-04-13 20:58
![scenario_with_multiple_rows](https://cloud.githubusercontent.com/assets/13576728/14509155/83a84768-0190-11e6-8d01-c588aa0dcdcf.png)

**Comment by YamStranger** [comment] 2016-04-14 04:37
@anujbajaj Thanks for issue.

**Comment by anujbajaj** [comment] 2016-04-14 14:48
Thanks @YamStranger.

@YamStranger @wakaleo 

Actually the thing we are trying to run a same story n times. Here n will be provided by the user otherwise we could have added more rows to the example tables in the story itself & would have implemented this. Hence we thought of adding rows at the run time based upon the user input but it is not working right now.

The another approach we thought of is calling findStoriesCalled() method & pass the same story name n times as a parameter however this works only if we only pass unique story names (as it is implemented as a Set & removing duplicate stories).

findStoriesCalled(abc.story;xyz.story) - It will execute both the stories.
findStoriesCalled(abc.story;abc.story) - It will execute abc.story once only. 

Is there any way that you can advice us till the time this issue is fixed as it is blocking us to implement an important functionality?

Regards,
Anuj

**Comment by YamStranger** [comment] 2016-04-14 15:02
@anujbajaj maybe it will be better to use 
```
...
@TestData                                                   
    public static Collection<Object[]> testData(){
        return Arrays.asList(new Object[][]{
                {0,     Bronze},
                {9999,  Bronze},
                {10000, Silver},
                {49999, Silver},
                {50000, Gold}
        });
    }

    private final int kilometersTravelled;                      
    private final Status expectedStatus;                        

    public WhenEarningFrequentFlyerStatusUpgrades(int kilometersTravelled, 
                                                  Status expectedStatus) { 
        this.kilometersTravelled = kilometersTravelled;
        this.expectedStatus = expectedStatus;
    }
...
```
or 
```
...
@RunWith(SerenityParameterizedRunner.class)
@UseTestDataFrom(value="testdata/status-levels.csv")                
public class WhenEarningFrequentFlyerStatusUpgradesUsingCSV {

    private int kilometersTravelled;
    private Status expectedStatus;

    public void setKilometersTravelled(int kilometersTravelled) {
        this.kilometersTravelled = kilometersTravelled;
    }

    public void setExpectedStatus(String expectedStatus) {
        this.expectedStatus = Status.valueOf(expectedStatus);
    }
....
```

Here is details: 
http://thucydides.info/docs/serenity-staging/#_data_driven_tests

**Comment by anujbajaj** [comment] 2016-04-14 16:12
Hi @YamStranger 

I believe these are the examples of data driven testing using Serenity.

We are using JBehave & the requirement is to run a same story multiple times with same set of data. With the above approach, I need to update my csv file or array-list every time before executing the tests to run it that many times.

In our requirement, we have the data within the JBehave story itself. The only thing which we need to control is the number of times that story should run & it will be provided by the user through Jenkins.

Regards,
Anuj

**Comment by YamStranger** [comment] 2016-04-14 16:57
@anujbajaj

I think that we can not support such requirement - execute some specific story several times. 

I thought that you need something like examples (for jbehave), but you need support quite specific behaving. 

You can do it using other tools on higher level, for example (and I understand that this approach quite "bad"), but it will be out of Serenity functionality:

For testing how jbehave works in parallel some test class is created:
https://github.com/serenity-bdd/serenity-module-integrations/blob/master/src/test/groovy/net/serenitybdd/modules/WhenBuildingJBehaveTestsInParallel.groovy

Internally this test copy same story and class N times and after that execute build (call gradle to execute build of some internal project). 

As I understand you - you can do something like that approach for your test:

1) clone stories as well as SerenityStories class with new name N times 
2) execute simple build. 

But you should be ready that in your report you will contains N test.

**Comment by anujbajaj** [comment] 2016-04-14 17:27
Thanks @YamStranger 

Will work on the workaround to get this done however if we can expedite the fix of this issue, it will be highly appreciated.

**Comment by YamStranger** [comment] 2016-04-14 17:54
@anujbajaj 
I think there is some misunderstanding, Serenity BDD for now does not define example table in Jbehave. 

In terms of JBehave: Serenity BDD provide Embeders and EmbedderMonitor and StoryReporter to follow test execution but not control it. 
During this execution Serenity BDD inject some resources, create report, initialize browser and so on. But Jbehave responsible for defining stories and examples for each scenario. 

If we return to first your message here - you try add some row in table row to force serenity run it. But Serenity BDD receive data table from Jbehave and can not change it, received data table used for reporting. 
Here is responsible line called during execution by JBehave [line](https://github.com/serenity-bdd/serenity-jbehave/blob/bd45c74b8ee33bb768e3f43b47b8a1cacc7bb74d/src/main/java/net/serenitybdd/jbehave/SerenityReporter.java#L660)

I believe that because of changes table rows during test execution you receive such strange report - for serenity all rows in all tests were executed successfully (by jbehave) and recorded, but amount of tests was updated (by your code) and were not the same as amount of executed tests. 

I think that you should native for jbehave way to define examples table during execution. 

This it not a bug of serenity, but this ticket can be marked as enhancement - idea of providing data table source in more advanced way that in JBehave sounds great

**Comment by wakaleo** [comment] 2017-11-02 09:13
We won't be implementing this, but PRs are welcome.

**Closed by wakaleo** 2017-11-02 09:13 UTC
Labels: enhancement, wontfix
